#!/usr/bin/env bash
#Install and configure HAproxy on a load-balancer server


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 5910-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 5910-web-02 44.192.66.59:80 check\n\tserver 5910-web-01 3.236.145.193:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
